CREATE TABLE IF NOT EXISTS lesson_comment_helpful_votes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    comment_id BIGINT NOT NULL REFERENCES lesson_comments(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_lesson_comment_helpful_vote UNIQUE (comment_id, user_id)
);

CREATE INDEX IF NOT EXISTS idx_lesson_comment_helpful_votes_comment
    ON lesson_comment_helpful_votes (comment_id);
