CREATE TABLE IF NOT EXISTS payment_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    txn_ref VARCHAR(36) NOT NULL UNIQUE,
    student_id BIGINT NOT NULL REFERENCES users(id),
    course_id BIGINT NOT NULL REFERENCES courses(id),
    amount NUMERIC(10, 2) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING'
        CHECK (status IN ('PENDING', 'PAID', 'FAILED')),
    vnp_transaction_no VARCHAR(64),
    bank_code VARCHAR(32),
    paid_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_payment_orders_student_id
    ON payment_orders (student_id);

CREATE INDEX IF NOT EXISTS idx_payment_orders_course_id
    ON payment_orders (course_id);
